services:
  - type: web
    name: zip-to-link
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: CLOUDFLARE_ACCOUNT_ID
        sync: false
      - key: CLOUDFLARE_API_TOKEN
        sync: false
      - key: CLOUDFLARE_PAGES_PROJECT_NAME
        value: crm-demo-sites
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
